/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ljch_helloworld_NDK */

#ifndef _Included_com_ljch_helloworld_NDK
#define _Included_com_ljch_helloworld_NDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ljch_helloworld_NDK
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ljch_helloworld_NDK_getStringFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
